export const LANGUAGES = [
    "English",
    "Spanish",
    "French",
    "German",
    "Mandarin",
    "Japanese",
    "Korean",
    "Hindi",
    "Russian",
    "Portuguese",
    "Arabic",
    "Italian",
    "Turkish",
    "Dutch",
  ];